using System;
using System.Collections.Generic;
using System.Text;

namespace ALISS.MasterManagement.Library.Models
{
    public class TCAntibiotic
    {
        public int ant_id { get; set; }
        public string ant_mst_code { get; set; }
        public string ant_code { get; set; }
        public string ant_name { get; set; }
        public string WHON5_CODE { get; set; }
        public string WHON4_CODE { get; set; }
        public string WHO_CODE { get; set; }
        public string DIN_CODE { get; set; }
        public string JAC_CODE { get; set; }
        public string USER_CODE { get; set; }
        public string ANTIBIOTIC { get; set; }
        public string GUIDELINES { get; set; }
        public string CLSI { get; set; }
        public string EUCAST { get; set; }
        public string SFM { get; set; }
        public string SRGA { get; set; }
        public string BSAC { get; set; }
        public string DIN { get; set; }
        public string NEO { get; set; }
        public string AFA { get; set; }
        public string ABX_NUMBER { get; set; }
        public string POTENCY { get; set; }
        public string BETALACTAM { get; set; }
        public string CLASS { get; set; }
        public string SUBCLASS { get; set; }
        public string PROF_CLASS { get; set; }
        public string CLSI_ORDER { get; set; }
        public string HUMAN { get; set; }
        public string VETERINARY { get; set; }
        public string ANIMAL_GP { get; set; }
        public string WHO_IMPORT { get; set; }
        public string LOINCCOMP { get; set; }
        public string LOINCGEN { get; set; }
        public string LOINCDISK { get; set; }
        public string LOINCMIC { get; set; }
        public string LOINCETEST { get; set; }
        public string LOINCSLOW { get; set; }
        public string LOINCAFB { get; set; }
        public string LOINCSBT { get; set; }
        public string LOINCMLC { get; set; }
        public string CLSI19_DR { get; set; }
        public string CLSI19_DI { get; set; }
        public string CLSI19_DS { get; set; }
        public string CLSI19_MS { get; set; }
        public string CLSI19_MR { get; set; }
        public string CLSI18_DR { get; set; }
        public string CLSI18_DI { get; set; }
        public string CLSI18_DS { get; set; }
        public string CLSI18_MS { get; set; }
        public string CLSI18_MR { get; set; }
        public string CLSI17_DR { get; set; }
        public string CLSI17_DI { get; set; }
        public string CLSI17_DS { get; set; }
        public string CLSI17_MS { get; set; }
        public string CLSI17_MR { get; set; }
        public string CLSI16_DR { get; set; }
        public string CLSI16_DI { get; set; }
        public string CLSI16_DS { get; set; }
        public string CLSI16_MS { get; set; }
        public string CLSI16_MR { get; set; }
        public string CLSI15_DR { get; set; }
        public string CLSI15_DI { get; set; }
        public string CLSI15_DS { get; set; }
        public string CLSI15_MS { get; set; }
        public string CLSI15_MR { get; set; }
        public string CLSI14_DR { get; set; }
        public string CLSI14_DI { get; set; }
        public string CLSI14_DS { get; set; }
        public string CLSI14_MS { get; set; }
        public string CLSI14_MR { get; set; }
        public string CLSI13_DR { get; set; }
        public string CLSI13_DI { get; set; }
        public string CLSI13_DS { get; set; }
        public string CLSI13_MS { get; set; }
        public string CLSI13_MR { get; set; }
        public string CLSI12_DR { get; set; }
        public string CLSI12_DI { get; set; }
        public string CLSI12_DS { get; set; }
        public string CLSI12_MS { get; set; }
        public string CLSI12_MR { get; set; }
        public string CLSI11_DR { get; set; }
        public string CLSI11_DI { get; set; }
        public string CLSI11_DS { get; set; }
        public string CLSI11_MS { get; set; }
        public string CLSI11_MR { get; set; }
        public string CLSI10_DR { get; set; }
        public string CLSI10_DI { get; set; }
        public string CLSI10_DS { get; set; }
        public string CLSI10_MS { get; set; }
        public string CLSI10_MR { get; set; }
        public string EUCST19_DR { get; set; }
        public string EUCST19_DI { get; set; }
        public string EUCST19_DS { get; set; }
        public string EUCST19_MS { get; set; }
        public string EUCST19_MR { get; set; }
        public string EUCST18_DR { get; set; }
        public string EUCST18_DI { get; set; }
        public string EUCST18_DS { get; set; }
        public string EUCST18_MS { get; set; }
        public string EUCST18_MR { get; set; }
        public string EUCST17_DR { get; set; }
        public string EUCST17_DI { get; set; }
        public string EUCST17_DS { get; set; }
        public string EUCST17_MS { get; set; }
        public string EUCST17_MR { get; set; }
        public string EUCST16_DR { get; set; }
        public string EUCST16_DI { get; set; }
        public string EUCST16_DS { get; set; }
        public string EUCST16_MS { get; set; }
        public string EUCST16_MR { get; set; }
        public string EUCST15_DR { get; set; }
        public string EUCST15_DI { get; set; }
        public string EUCST15_DS { get; set; }
        public string EUCST15_MS { get; set; }
        public string EUCST15_MR { get; set; }
        public string EUCST14_DR { get; set; }
        public string EUCST14_DI { get; set; }
        public string EUCST14_DS { get; set; }
        public string EUCST14_MS { get; set; }
        public string EUCST14_MR { get; set; }
        public string EUCST13_DR { get; set; }
        public string EUCST13_DI { get; set; }
        public string EUCST13_DS { get; set; }
        public string EUCST13_MS { get; set; }
        public string EUCST13_MR { get; set; }
        public string ECV12_DR { get; set; }
        public string ECV12_DI { get; set; }
        public string ECV12_DS { get; set; }
        public string ECV12_MS { get; set; }
        public string ECV12_MR { get; set; }
        public string EUCST11_DR { get; set; }
        public string EUCST11_DI { get; set; }
        public string EUCST11_DS { get; set; }
        public string EUCST11_MS { get; set; }
        public string EUCST11_MR { get; set; }
        public string NEODK16_DR { get; set; }
        public string NEODK16_DI { get; set; }
        public string NEODK16_DS { get; set; }
        public string NEODK16_MS { get; set; }
        public string NEODK16_MR { get; set; }
        public string NEODK13_DR { get; set; }
        public string NEODK13_DI { get; set; }
        public string NEODK13_DS { get; set; }
        public string NEODK13_MS { get; set; }
        public string NEODK13_MR { get; set; }
        public string NEODK98_DR { get; set; }
        public string NEODK98_DI { get; set; }
        public string NEODK98_DS { get; set; }
        public string NEODK98_MS { get; set; }
        public string NEODK98_MR { get; set; }
        public string SFM07_DR { get; set; }
        public string SFM07_DI { get; set; }
        public string SFM07_DS { get; set; }
        public string SFM07_MS { get; set; }
        public string SFM07_MR { get; set; }
        public string DIN04_DR { get; set; }
        public string DIN04_DI { get; set; }
        public string DIN04_DS { get; set; }
        public string DIN04_MS { get; set; }
        public string DIN04_MR { get; set; }
        public string CRG96_DR { get; set; }
        public string CRG96_DI { get; set; }
        public string CRG96_DS { get; set; }
        public string CRG96_MS { get; set; }
        public string CRG96_MR { get; set; }
        public string AFA00_DR { get; set; }
        public string AFA00_DI { get; set; }
        public string AFA00_DS { get; set; }
        public string AFA00_MS { get; set; }
        public string AFA00_MR { get; set; }
        public string MENS00_DR { get; set; }
        public string MENS00_DI { get; set; }
        public string MENS00_DS { get; set; }
        public string MENS00_MS { get; set; }
        public string MENS00_MR { get; set; }
        public string SRGA98_DR { get; set; }
        public string SRGA98_DI { get; set; }
        public string SRGA98_DS { get; set; }
        public string SRGA98_MS { get; set; }
        public string SRGA98_MR { get; set; }
        public string BSAC00_DR { get; set; }
        public string BSAC00_DI { get; set; }
        public string BSAC00_DS { get; set; }
        public string BSAC00_MS { get; set; }
        public string BSAC00_MR { get; set; }
        public string OTHER_DR { get; set; }
        public string OTHER_DI { get; set; }
        public string OTHER_DS { get; set; }
        public string OTHER_MS { get; set; }
        public string OTHER_MR { get; set; }
        public string ant_status { get; set; }
        public bool ant_active { get; set; }
        public string ant_createuser { get; set; }
        public DateTime? ant_createdate { get; set; }
        public string ant_updateuser { get; set; }
        public DateTime? ant_updatedate { get; set; }
    }
}
