//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALISS.EXPORT.Library.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ALISSEntities : DbContext
    {
        public ALISSEntities()
            : base("name=ALISSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_GET_RPAntibicromialResistance_Result> sp_GET_RPAntibicromialResistance(string org_codes, string anti_codes, int start_year, int end_year)
        {
            var org_codesParameter = org_codes != null ?
                new ObjectParameter("org_codes", org_codes) :
                new ObjectParameter("org_codes", typeof(string));
    
            var anti_codesParameter = anti_codes != null ?
                new ObjectParameter("anti_codes", anti_codes) :
                new ObjectParameter("anti_codes", typeof(string));
    
            var start_yearParameter = start_year != 0 ?
                new ObjectParameter("start_year", start_year) :
                new ObjectParameter("start_year", typeof(int));
    
            var end_yearParameter = end_year != 0 ?
                new ObjectParameter("end_year", end_year) :
                new ObjectParameter("end_year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_RPAntibicromialResistance_Result>("sp_GET_RPAntibicromialResistance", org_codesParameter, anti_codesParameter, start_yearParameter, end_yearParameter);
        }
    
        public virtual ObjectResult<sp_GET_RPAntibiotrendAMRStrategy_Result> sp_GET_RPAntibiotrendAMRStrategy(System.DateTime month_start, System.DateTime month_end)
        {
            var month_startParameter = month_start != null ?
                new ObjectParameter("month_start", month_start) :
                new ObjectParameter("month_start", typeof(System.DateTime));
    
            var month_endParameter = month_end != null ?
                new ObjectParameter("month_end", month_end) :
                new ObjectParameter("month_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_RPAntibiotrendAMRStrategy_Result>("sp_GET_RPAntibiotrendAMRStrategy", month_startParameter, month_endParameter);
        }
    
        public virtual ObjectResult<sp_GET_TCSpecimen_Active_Result> sp_GET_TCSpecimen_Active(string spc_mst_code)
        {
            var spc_mst_codeParameter = spc_mst_code != null ?
                new ObjectParameter("spc_mst_code", spc_mst_code) :
                new ObjectParameter("spc_mst_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_TCSpecimen_Active_Result>("sp_GET_TCSpecimen_Active", spc_mst_codeParameter);
        }
    
        public virtual ObjectResult<sp_GET_TCWardType_Active_Result> sp_GET_TCWardType_Active(string wrd_mst_code)
        {
            var wrd_mst_codeParameter = wrd_mst_code != null ?
                new ObjectParameter("wrd_mst_code", wrd_mst_code) :
                new ObjectParameter("wrd_mst_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_TCWardType_Active_Result>("sp_GET_TCWardType_Active", wrd_mst_codeParameter);
        }
    
        public virtual ObjectResult<sp_GET_TCAntibiotic_Active_Result> sp_GET_TCAntibiotic_Active(string ant_mst_code)
        {
            var ant_mst_codeParameter = ant_mst_code != null ?
                new ObjectParameter("ant_mst_code", ant_mst_code) :
                new ObjectParameter("ant_mst_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_TCAntibiotic_Active_Result>("sp_GET_TCAntibiotic_Active", ant_mst_codeParameter);
        }
    
        public virtual ObjectResult<sp_GET_TCOrganism_Active_Result> sp_GET_TCOrganism_Active(string org_mst_code)
        {
            var org_mst_codeParameter = org_mst_code != null ?
                new ObjectParameter("org_mst_code", org_mst_code) :
                new ObjectParameter("org_mst_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_TCOrganism_Active_Result>("sp_GET_TCOrganism_Active", org_mst_codeParameter);
        }
    
        public virtual ObjectResult<sp_GET_TCParameter_Result> sp_GET_TCParameter(string prm_code_major)
        {
            var prm_code_majorParameter = prm_code_major != null ?
                new ObjectParameter("prm_code_major", prm_code_major) :
                new ObjectParameter("prm_code_major", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_TCParameter_Result>("sp_GET_TCParameter", prm_code_majorParameter);
        }
    
        public virtual ObjectResult<sp_GET_RPAntibicromialResstAll_Result> sp_GET_RPAntibicromialResstAll(string org_codes, string anti_codes, int start_year, int end_year)
        {
            var org_codesParameter = org_codes != null ?
                new ObjectParameter("org_codes", org_codes) :
                new ObjectParameter("org_codes", typeof(string));
    
            var anti_codesParameter = anti_codes != null ?
                new ObjectParameter("anti_codes", anti_codes) :
                new ObjectParameter("anti_codes", typeof(string));
    
            var start_yearParameter = start_year != 0 ?
                new ObjectParameter("start_year", start_year) :
                new ObjectParameter("start_year", typeof(int));
    
            var end_yearParameter = end_year != 0 ?
                new ObjectParameter("end_year", end_year) :
                new ObjectParameter("end_year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_RPAntibicromialResstAll_Result>("sp_GET_RPAntibicromialResstAll", org_codesParameter, anti_codesParameter, start_yearParameter, end_yearParameter);
        }
    
        public virtual ObjectResult<sp_GET_RPAntibicromialResstSpecimen_Result> sp_GET_RPAntibicromialResstSpecimen(string org_codes, string anti_codes, int start_year, int end_year)
        {
            var org_codesParameter = org_codes != null ?
                new ObjectParameter("org_codes", org_codes) :
                new ObjectParameter("org_codes", typeof(string));
    
            var anti_codesParameter = anti_codes != null ?
                new ObjectParameter("anti_codes", anti_codes) :
                new ObjectParameter("anti_codes", typeof(string));
    
            var start_yearParameter = start_year != 0 ?
                new ObjectParameter("start_year", start_year) :
                new ObjectParameter("start_year", typeof(int));
    
            var end_yearParameter = end_year != 0 ?
                new ObjectParameter("end_year", end_year) :
                new ObjectParameter("end_year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_RPAntibicromialResstSpecimen_Result>("sp_GET_RPAntibicromialResstSpecimen", org_codesParameter, anti_codesParameter, start_yearParameter, end_yearParameter);
        }
    
        public virtual ObjectResult<sp_GET_RPAntibicromialResstWard_Result> sp_GET_RPAntibicromialResstWard(string org_codes, string anti_codes, int start_year, int end_year)
        {
            var org_codesParameter = org_codes != null ?
                new ObjectParameter("org_codes", org_codes) :
                new ObjectParameter("org_codes", typeof(string));
    
            var anti_codesParameter = anti_codes != null ?
                new ObjectParameter("anti_codes", anti_codes) :
                new ObjectParameter("anti_codes", typeof(string));
    
            var start_yearParameter = start_year != 0 ?
                new ObjectParameter("start_year", start_year) :
                new ObjectParameter("start_year", typeof(int));
    
            var end_yearParameter = end_year != 0 ?
                new ObjectParameter("end_year", end_year) :
                new ObjectParameter("end_year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GET_RPAntibicromialResstWard_Result>("sp_GET_RPAntibicromialResstWard", org_codesParameter, anti_codesParameter, start_yearParameter, end_yearParameter);
        }
    }
}
