using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace ALISS.MasterManagement.DTO
{
    public class AntibioticDTO
    {
        public int ant_id { get; set; }
        public string ant_mst_code { get; set; }
        [Required(ErrorMessage = "* Please enter antibiotic code")]
        [RegularExpression("([a-zA-Z0-9_'-]+)", ErrorMessage = "Wrong format.")]
        public string ant_code { get; set; }
        [Required(ErrorMessage = "* Please enter antibiotic name")]
        public string ant_name { get; set; }
        public string ant_mst_WHON5_CODE { get; set; }
        public string ant_mst_WHON4_CODE { get; set; }
        public string ant_mst_WHO_CODE { get; set; }
        public string ant_mst_DIN_CODE { get; set; }
        public string ant_mst_JAC_CODE { get; set; }
        public string ant_mst_USER_CODE { get; set; }
        public string ant_mst_ANTIBIOTIC { get; set; }
        public string ant_mst_GUIDELINES { get; set; }
        public string ant_mst_CLSI { get; set; }
        public string ant_mst_EUCAST { get; set; }
        public string ant_mst_SFM { get; set; }
        public string ant_mst_SRGA { get; set; }
        public string ant_mst_BSAC { get; set; }
        public string ant_mst_DIN { get; set; }
        public string ant_mst_NEO { get; set; }
        public string ant_mst_AFA { get; set; }
        public string ant_mst_ABX_NUMBER { get; set; }
        public string ant_mst_POTENCY { get; set; }
        public string ant_mst_BETALACTAM { get; set; }
        public string ant_mst_CLASS { get; set; }
        public string ant_mst_SUBCLASS { get; set; }
        public string ant_mst_PROF_CLASS { get; set; }
        public string ant_mst_CLSI_ORDER { get; set; }
        public string ant_mst_HUMAN { get; set; }
        public string ant_mst_VETERINARY { get; set; }
        public string ant_mst_ANIMAL_GP { get; set; }
        public string ant_mst_WHO_IMPORT { get; set; }
        public string ant_mst_LOINCCOMP { get; set; }
        public string ant_mst_LOINCGEN { get; set; }
        public string ant_mst_LOINCDISK { get; set; }
        public string ant_mst_LOINCMIC { get; set; }
        public string ant_mst_LOINCETEST { get; set; }
        public string ant_mst_LOINCSLOW { get; set; }
        public string ant_mst_LOINCAFB { get; set; }
        public string ant_mst_LOINCSBT { get; set; }
        public string ant_mst_LOINCMLC { get; set; }
        public string ant_mst_CLSI19_DR { get; set; }
        public string ant_mst_CLSI19_DI { get; set; }
        public string ant_mst_CLSI19_DS { get; set; }
        public string ant_mst_CLSI19_MS { get; set; }
        public string ant_mst_CLSI19_MR { get; set; }
        public string ant_mst_CLSI18_DR { get; set; }
        public string ant_mst_CLSI18_DI { get; set; }
        public string ant_mst_CLSI18_DS { get; set; }
        public string ant_mst_CLSI18_MS { get; set; }
        public string ant_mst_CLSI18_MR { get; set; }
        public string ant_mst_CLSI17_DR { get; set; }
        public string ant_mst_CLSI17_DI { get; set; }
        public string ant_mst_CLSI17_DS { get; set; }
        public string ant_mst_CLSI17_MS { get; set; }
        public string ant_mst_CLSI17_MR { get; set; }
        public string ant_mst_CLSI16_DR { get; set; }
        public string ant_mst_CLSI16_DI { get; set; }
        public string ant_mst_CLSI16_DS { get; set; }
        public string ant_mst_CLSI16_MS { get; set; }
        public string ant_mst_CLSI16_MR { get; set; }
        public string ant_mst_CLSI15_DR { get; set; }
        public string ant_mst_CLSI15_DI { get; set; }
        public string ant_mst_CLSI15_DS { get; set; }
        public string ant_mst_CLSI15_MS { get; set; }
        public string ant_mst_CLSI15_MR { get; set; }
        public string ant_mst_CLSI14_DR { get; set; }
        public string ant_mst_CLSI14_DI { get; set; }
        public string ant_mst_CLSI14_DS { get; set; }
        public string ant_mst_CLSI14_MS { get; set; }
        public string ant_mst_CLSI14_MR { get; set; }
        public string ant_mst_CLSI13_DR { get; set; }
        public string ant_mst_CLSI13_DI { get; set; }
        public string ant_mst_CLSI13_DS { get; set; }
        public string ant_mst_CLSI13_MS { get; set; }
        public string ant_mst_CLSI13_MR { get; set; }
        public string ant_mst_CLSI12_DR { get; set; }
        public string ant_mst_CLSI12_DI { get; set; }
        public string ant_mst_CLSI12_DS { get; set; }
        public string ant_mst_CLSI12_MS { get; set; }
        public string ant_mst_CLSI12_MR { get; set; }
        public string ant_mst_CLSI11_DR { get; set; }
        public string ant_mst_CLSI11_DI { get; set; }
        public string ant_mst_CLSI11_DS { get; set; }
        public string ant_mst_CLSI11_MS { get; set; }
        public string ant_mst_CLSI11_MR { get; set; }
        public string ant_mst_CLSI10_DR { get; set; }
        public string ant_mst_CLSI10_DI { get; set; }
        public string ant_mst_CLSI10_DS { get; set; }
        public string ant_mst_CLSI10_MS { get; set; }
        public string ant_mst_CLSI10_MR { get; set; }
        public string ant_mst_EUCST19_DR { get; set; }
        public string ant_mst_EUCST19_DI { get; set; }
        public string ant_mst_EUCST19_DS { get; set; }
        public string ant_mst_EUCST19_MS { get; set; }
        public string ant_mst_EUCST19_MR { get; set; }
        public string ant_mst_EUCST18_DR { get; set; }
        public string ant_mst_EUCST18_DI { get; set; }
        public string ant_mst_EUCST18_DS { get; set; }
        public string ant_mst_EUCST18_MS { get; set; }
        public string ant_mst_EUCST18_MR { get; set; }
        public string ant_mst_EUCST17_DR { get; set; }
        public string ant_mst_EUCST17_DI { get; set; }
        public string ant_mst_EUCST17_DS { get; set; }
        public string ant_mst_EUCST17_MS { get; set; }
        public string ant_mst_EUCST17_MR { get; set; }
        public string ant_mst_EUCST16_DR { get; set; }
        public string ant_mst_EUCST16_DI { get; set; }
        public string ant_mst_EUCST16_DS { get; set; }
        public string ant_mst_EUCST16_MS { get; set; }
        public string ant_mst_EUCST16_MR { get; set; }
        public string ant_mst_EUCST15_DR { get; set; }
        public string ant_mst_EUCST15_DI { get; set; }
        public string ant_mst_EUCST15_DS { get; set; }
        public string ant_mst_EUCST15_MS { get; set; }
        public string ant_mst_EUCST15_MR { get; set; }
        public string ant_mst_EUCST14_DR { get; set; }
        public string ant_mst_EUCST14_DI { get; set; }
        public string ant_mst_EUCST14_DS { get; set; }
        public string ant_mst_EUCST14_MS { get; set; }
        public string ant_mst_EUCST14_MR { get; set; }
        public string ant_mst_EUCST13_DR { get; set; }
        public string ant_mst_EUCST13_DI { get; set; }
        public string ant_mst_EUCST13_DS { get; set; }
        public string ant_mst_EUCST13_MS { get; set; }
        public string ant_mst_EUCST13_MR { get; set; }
        public string ant_mst_ECV12_DR { get; set; }
        public string ant_mst_ECV12_DI { get; set; }
        public string ant_mst_ECV12_DS { get; set; }
        public string ant_mst_ECV12_MS { get; set; }
        public string ant_mst_ECV12_MR { get; set; }
        public string ant_mst_EUCST11_DR { get; set; }
        public string ant_mst_EUCST11_DI { get; set; }
        public string ant_mst_EUCST11_DS { get; set; }
        public string ant_mst_EUCST11_MS { get; set; }
        public string ant_mst_EUCST11_MR { get; set; }
        public string ant_mst_NEODK16_DR { get; set; }
        public string ant_mst_NEODK16_DI { get; set; }
        public string ant_mst_NEODK16_DS { get; set; }
        public string ant_mst_NEODK16_MS { get; set; }
        public string ant_mst_NEODK16_MR { get; set; }
        public string ant_mst_NEODK13_DR { get; set; }
        public string ant_mst_NEODK13_DI { get; set; }
        public string ant_mst_NEODK13_DS { get; set; }
        public string ant_mst_NEODK13_MS { get; set; }
        public string ant_mst_NEODK13_MR { get; set; }
        public string ant_mst_NEODK98_DR { get; set; }
        public string ant_mst_NEODK98_DI { get; set; }
        public string ant_mst_NEODK98_DS { get; set; }
        public string ant_mst_NEODK98_MS { get; set; }
        public string ant_mst_NEODK98_MR { get; set; }
        public string ant_mst_SFM07_DR { get; set; }
        public string ant_mst_SFM07_DI { get; set; }
        public string ant_mst_SFM07_DS { get; set; }
        public string ant_mst_SFM07_MS { get; set; }
        public string ant_mst_SFM07_MR { get; set; }
        public string ant_mst_DIN04_DR { get; set; }
        public string ant_mst_DIN04_DI { get; set; }
        public string ant_mst_DIN04_DS { get; set; }
        public string ant_mst_DIN04_MS { get; set; }
        public string ant_mst_DIN04_MR { get; set; }
        public string ant_mst_CRG96_DR { get; set; }
        public string ant_mst_CRG96_DI { get; set; }
        public string ant_mst_CRG96_DS { get; set; }
        public string ant_mst_CRG96_MS { get; set; }
        public string ant_mst_CRG96_MR { get; set; }
        public string ant_mst_AFA00_DR { get; set; }
        public string ant_mst_AFA00_DI { get; set; }
        public string ant_mst_AFA00_DS { get; set; }
        public string ant_mst_AFA00_MS { get; set; }
        public string ant_mst_AFA00_MR { get; set; }
        public string ant_mst_MENS00_DR { get; set; }
        public string ant_mst_MENS00_DI { get; set; }
        public string ant_mst_MENS00_DS { get; set; }
        public string ant_mst_MENS00_MS { get; set; }
        public string ant_mst_MENS00_MR { get; set; }
        public string ant_mst_SRGA98_DR { get; set; }
        public string ant_mst_SRGA98_DI { get; set; }
        public string ant_mst_SRGA98_DS { get; set; }
        public string ant_mst_SRGA98_MS { get; set; }
        public string ant_mst_SRGA98_MR { get; set; }
        public string ant_mst_BSAC00_DR { get; set; }
        public string ant_mst_BSAC00_DI { get; set; }
        public string ant_mst_BSAC00_DS { get; set; }
        public string ant_mst_BSAC00_MS { get; set; }
        public string ant_mst_BSAC00_MR { get; set; }
        public string ant_mst_OTHER_DR { get; set; }
        public string ant_mst_OTHER_DI { get; set; }
        public string ant_mst_OTHER_DS { get; set; }
        public string ant_mst_OTHER_MS { get; set; }
        public string ant_mst_OTHER_MR { get; set; }
        public string ant_status { get; set; }
        public bool ant_active { get; set; }
        public string ant_createuser { get; set; }
        public DateTime? ant_createdate { get; set; }
        public string ant_updateuser { get; set; }
        public DateTime? ant_updatedate { get; set; }
    }
}
